trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 180
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
  - bash: bash ./docker_build.sh
  - task: CopyFiles@2
    inputs:
      Contents: |
        release/**
      targetFolder: $(Build.ArtifactStagingDirectory)
  - bash: ls -al $(Build.ArtifactStagingDirectory)
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: '13pgeiser_azure'
      repositoryName: '13pgeiser/gcc-x86_64-w64-mingw32-multilib'
      action: 'create'
      assets: '$(Build.ArtifactStagingDirectory)/release/*'

